"""Polymarket data-api historical trade backfiller.

Replaces the original "on-chain trade replay via Polygon archive node"
plan with a much simpler ingestion: data-api.polymarket.com/trades is
a public REST endpoint that returns the same data (matched fills with
maker/taker wallets, prices, sizes, transaction hashes) without any
archive-node dependency.

Endpoint shape:

  GET /trades?market=<conditionId>&limit=<int>&offset=<int>
       &filterType=<HASH|CASH>&filterAmount=<min_usd>

Returns a JSON array of trade objects:

  {
    "proxyWallet":      "0x...",
    "side":             "BUY" | "SELL",
    "asset":            "<token_id_decimal>",
    "conditionId":      "0x...",
    "size":             float,
    "price":            float,
    "timestamp":        unix_seconds,
    "transactionHash":  "0x...",
    "title":            <market question>,
    "name":             <user display name, may be empty>,
    "pseudonym":        <auto-generated user handle>,
    ...
  }

Pagination is via `offset` (verified working at limit=100 increments).
The endpoint returns the most recent trades first.

Persistence: new `historical_trades` table with the schema mirroring
the API response, plus indices on (market, ts), (wallet, ts) for the
common backfill queries (smart-money ranking, per-market validation,
NegRisk-pair detection).
"""
from __future__ import annotations

import asyncio
import sqlite3
import time
from dataclasses import dataclass, field

import aiohttp
import structlog

log = structlog.get_logger()


DATA_API = "https://data-api.polymarket.com"
PAGE_LIMIT = 500          # API tolerates up to 500 per page
REQUEST_TIMEOUT_SEC = 20
INTER_REQUEST_DELAY_SEC = 0.10  # 10 req/sec, well under public rate limits


def ensure_table(conn: sqlite3.Connection) -> None:
    conn.execute(
        """CREATE TABLE IF NOT EXISTS historical_trades (
            tx_hash       TEXT NOT NULL,
            wallet        TEXT NOT NULL,
            asset         TEXT NOT NULL,
            condition_id  TEXT NOT NULL,
            side          TEXT NOT NULL,
            outcome       TEXT,
            outcome_index INTEGER,
            size          REAL NOT NULL,
            price         REAL NOT NULL,
            ts            REAL NOT NULL,
            title         TEXT,
            slug          TEXT,
            event_slug    TEXT,
            display_name  TEXT,
            pseudonym     TEXT,
            PRIMARY KEY (tx_hash, wallet, asset, side, size, price)
        )"""
    )
    conn.execute("CREATE INDEX IF NOT EXISTS hist_trade_market_ts ON historical_trades(condition_id, ts)")
    conn.execute("CREATE INDEX IF NOT EXISTS hist_trade_wallet_ts ON historical_trades(wallet, ts)")
    conn.execute("CREATE INDEX IF NOT EXISTS hist_trade_ts ON historical_trades(ts)")
    conn.commit()


@dataclass
class TradeBackfillSummary:
    fetched: int = 0
    inserted: int = 0
    duplicates: int = 0
    pages: int = 0
    errors: int = 0
    started_ts: float = field(default_factory=time.time)
    earliest_ts: float | None = None
    latest_ts: float | None = None


# ── HTTP fetch ──────────────────────────────────────────────────────────
async def fetch_page(
    session: aiohttp.ClientSession,
    *,
    market: str | None = None,
    user: str | None = None,
    limit: int = PAGE_LIMIT,
    offset: int = 0,
) -> list[dict]:
    """Fetch one page of trades. Returns the raw JSON list (possibly empty)."""
    params: dict = {"limit": str(limit), "offset": str(offset)}
    if market:
        params["market"] = market
    if user:
        params["user"] = user
    try:
        async with session.get(
            f"{DATA_API}/trades", params=params,
            timeout=aiohttp.ClientTimeout(total=REQUEST_TIMEOUT_SEC),
        ) as r:
            if r.status != 200:
                log.warning("polymarket_trades_http", status=r.status, offset=offset)
                return []
            data = await r.json()
            if not isinstance(data, list):
                log.warning("polymarket_trades_unexpected_response", type=str(type(data)))
                return []
            return data
    except (aiohttp.ClientError, asyncio.TimeoutError) as e:
        log.warning("polymarket_trades_error", err=str(e), offset=offset)
        return []


# ── Persistence ─────────────────────────────────────────────────────────
def insert_trades(conn: sqlite3.Connection, trades: list[dict]) -> tuple[int, int]:
    """Insert OR IGNORE a batch. Returns (inserted, duplicate_count)."""
    ensure_table(conn)
    inserted = 0
    duplicates = 0
    for t in trades:
        try:
            cur = conn.execute(
                """INSERT OR IGNORE INTO historical_trades
                   (tx_hash, wallet, asset, condition_id, side, outcome,
                    outcome_index, size, price, ts, title, slug,
                    event_slug, display_name, pseudonym)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    str(t.get("transactionHash") or ""),
                    str(t.get("proxyWallet") or "").lower(),
                    str(t.get("asset") or ""),
                    str(t.get("conditionId") or ""),
                    str(t.get("side") or ""),
                    t.get("outcome"),
                    int(t.get("outcomeIndex") or 0),
                    float(t.get("size") or 0.0),
                    float(t.get("price") or 0.0),
                    float(t.get("timestamp") or 0.0),
                    t.get("title"),
                    t.get("slug"),
                    t.get("eventSlug"),
                    t.get("name"),
                    t.get("pseudonym"),
                ),
            )
            if cur.rowcount > 0:
                inserted += 1
            else:
                duplicates += 1
        except (sqlite3.OperationalError, ValueError, TypeError) as e:
            log.warning("trade_insert_skip", err=str(e))
    conn.commit()
    return inserted, duplicates


# ── Backfill loops ──────────────────────────────────────────────────────
async def backfill_market(
    db_path: str,
    condition_id: str,
    *,
    max_pages: int = 200,
    earliest_ts: float | None = None,
) -> TradeBackfillSummary:
    """Page through trades for a single market, oldest direction first
    via offset pagination. Stop when an empty page returns OR we cross
    earliest_ts OR max_pages reached."""
    summary = TradeBackfillSummary()
    conn = sqlite3.connect(db_path, timeout=10.0)
    ensure_table(conn)
    async with aiohttp.ClientSession() as session:
        offset = 0
        for page in range(max_pages):
            trades = await fetch_page(session, market=condition_id, offset=offset)
            summary.pages += 1
            if not trades:
                break
            summary.fetched += len(trades)
            ins, dup = insert_trades(conn, trades)
            summary.inserted += ins
            summary.duplicates += dup
            page_min_ts = min(float(t.get("timestamp", 0)) for t in trades)
            page_max_ts = max(float(t.get("timestamp", 0)) for t in trades)
            summary.earliest_ts = (
                page_min_ts if summary.earliest_ts is None else min(summary.earliest_ts, page_min_ts)
            )
            summary.latest_ts = (
                page_max_ts if summary.latest_ts is None else max(summary.latest_ts, page_max_ts)
            )
            if earliest_ts is not None and page_min_ts <= earliest_ts:
                break
            if len(trades) < PAGE_LIMIT:
                # Last page (fewer results than the page size)
                break
            offset += PAGE_LIMIT
            await asyncio.sleep(INTER_REQUEST_DELAY_SEC)
    conn.close()
    return summary


async def backfill_global(
    db_path: str,
    *,
    max_pages: int = 200,
    earliest_ts: float | None = None,
) -> TradeBackfillSummary:
    """Page through the global recent-trades stream (no market filter).

    Useful for a fast smart-money seed: walk the most-recent ~100k trades
    across the whole exchange to populate the wallet-volume rankings.
    """
    summary = TradeBackfillSummary()
    conn = sqlite3.connect(db_path, timeout=10.0)
    ensure_table(conn)
    async with aiohttp.ClientSession() as session:
        offset = 0
        for page in range(max_pages):
            trades = await fetch_page(session, offset=offset)
            summary.pages += 1
            if not trades:
                break
            summary.fetched += len(trades)
            ins, dup = insert_trades(conn, trades)
            summary.inserted += ins
            summary.duplicates += dup
            page_min_ts = min(float(t.get("timestamp", 0)) for t in trades)
            page_max_ts = max(float(t.get("timestamp", 0)) for t in trades)
            summary.earliest_ts = (
                page_min_ts if summary.earliest_ts is None else min(summary.earliest_ts, page_min_ts)
            )
            summary.latest_ts = (
                page_max_ts if summary.latest_ts is None else max(summary.latest_ts, page_max_ts)
            )
            if earliest_ts is not None and page_min_ts <= earliest_ts:
                break
            if len(trades) < PAGE_LIMIT:
                break
            offset += PAGE_LIMIT
            await asyncio.sleep(INTER_REQUEST_DELAY_SEC)
    conn.close()
    return summary


# ── Smart-money computation from the tape ──────────────────────────────
def top_volume_wallets(
    db_path: str,
    *,
    days: int = 30,
    top_k: int = 200,
    min_usdc_volume: float = 10000.0,
) -> list[dict]:
    """Compute top-K wallets by USDC notional traded over the last `days`.

    USDC notional ≈ size × price (each token = $1 at resolution).
    Returns descending-sorted list of {wallet, total_volume, n_trades,
    first_ts, last_ts}.
    """
    cutoff = time.time() - days * 86400
    conn = sqlite3.connect(db_path)
    rows = conn.execute(
        """SELECT
              wallet,
              ROUND(SUM(size * price), 2) AS volume,
              COUNT(*) AS n,
              MIN(ts) AS first_ts,
              MAX(ts) AS last_ts
           FROM historical_trades
           WHERE ts >= ?
           GROUP BY wallet
           HAVING volume >= ?
           ORDER BY volume DESC
           LIMIT ?""",
        (cutoff, min_usdc_volume, top_k),
    ).fetchall()
    conn.close()
    return [
        {"wallet": r[0], "volume": r[1], "n_trades": r[2],
         "first_ts": r[3], "last_ts": r[4]}
        for r in rows
    ]
